#+TITLE: UKR
#+AUTHOR: Tiitus Järvinen

* Objectives

** TODO Poster background completion
   Currently the poster background contains only the label for the currently playing item.

*** [#A] Movies
    * Title
    * Year
    * Director
    * Rating
    * Duration?

*** [#B] TV
    Same as movies, but producers instead of directors. Additionally:
    * Season
    * Episode

*** [#C] Audio
    * Year
    * Rating
    * Disc
    * Track number
    * Artist
    * Album

** TODO [#A] Seekbar
   Implement the seekbar properly. Currently has a placeholder but does not work.

** TODO [#B] Playlist Support

** TODO Content browsing

*** TODO [#C] Add-Ons
    Browse All add-ons quickly and efficiently.
    Should be quickly accessible from the remote screen.
    
*** TODO Files
    Not nearly as important, as I don't really use this feature all that much yet.
    
* Known Issues / Bugs

** TODO Launch Screen render error
   Flashes for a little while when opening the application for the first time. Should be easily fixed by implementing null player item check.
   
** TODO Playback controls overflow error
   Control buttons overflow on very narrow screen. As this is written, implemented by the following line:

    #+BEGIN_SRC dart
      final _contSize = min(40.0, MediaQuery.of(context).size.width / 6 - 28.0);
    #+END_SRC
