name: Build_Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java to compile Android project
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.6.2
        with:
          flutter-version: '2.x'
          channel: 'stable'

      - name: Restore packages
        run: flutter pub get

      - name: Build Android App
        run: flutter build apk --release

      - name: Publish Android Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk-debug
          path: build/app/outputs/flutter-apk/*.apk
